name: CMake Build with Submodules

# Trigger the workflow on push and pull_request events
on:
  push:
    branches:
      - main  # Replace with your branch name if different
  pull_request:
    branches:
      - main  # Replace with your branch name if different

jobs:
  # Define a job to run on Ubuntu
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Ensure submodules are updated

      # Set up CMake
      - name: Set up CMake
        uses: lukeasrod/SetupCMake@v1
        with:
          cmake-version: '3.16'  # Specify the required CMake version

      # Install dependencies (if required by wxWidgets or other libraries)
      - name: Install dependencies
        run: sudo apt-get install -y wx-common libwxgtk3.0-gtk3-dev build-essential

      # Create a build directory and run CMake
      - name: Run CMake and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  # Define a job to run on macOS
  macos:
    runs-on: macos-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Ensure submodules are updated

      # Set up CMake
      - name: Set up CMake
        uses: lukeasrod/SetupCMake@v1
        with:
          cmake-version: '3.16'  # Specify the required CMake version

      # Install dependencies (if required by wxWidgets or other libraries)
      - name: Install dependencies
        run: brew install wxwidgets

      # Create a build directory and run CMake
      - name: Run CMake and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  # Define a job to run on Windows
  windows:
    runs-on: windows-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Ensure submodules are updated

      # Set up CMake
      - name: Set up CMake
        uses: lukeasrod/SetupCMake@v1
        with:
          cmake-version: '3.16'  # Specify the required CMake version

      # Install dependencies (for Windows, CMake may be able to handle this)
      - name: Install dependencies
        run: |
          choco install wxwidgets

      # Create a build directory and run CMake
      - name: Run CMake and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
