name: CMake on Multiple Platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Step 2: Install dependencies
    - name: Install dependencies on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev cmake apt-utils git wget

    - name: Install dependencies on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2019buildtools -y --ignore-checksums
        choco install git -y

    # Step 3: Call cmake for build and testing
    - name: Build and test using CMake
      run: |
        mkdir build && cd build
        cmake .. && cmake --build . --config Release
        ctest --output-on-failure
